# Generated by Django 4.2.2 on 2024-01-20 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name of the type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name of the type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.CharField(blank=True, max_length=256, null=True, verbose_name='Latitude')),
                ('long', models.CharField(blank=True, max_length=256, null=True, verbose_name='Longtitude')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address of the property')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is this property available')),
                ('is_rent', models.BooleanField(default=True, verbose_name='Is this property being rented, or sold?')),
                ('misc', models.JSONField(blank=True, null=True, verbose_name='Other details in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('township', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_manager.township')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_manager.propertytype')),
            ],
        ),
    ]
