# Generated by Django 4.2.2 on 2024-01-20 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Monthly Price/Sale Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='added_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='township',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='name of the township'),
        ),
    ]
